version: '3.8'

services:
  postgresql:
    image: postgres:13.4-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=testUser
      - POSTGRES_DB=testDB